# Generated by Django 3.0.6 on 2020-05-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
