# Generated by Django 3.0.6 on 2020-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='email',
        ),
        migrations.RemoveField(
            model_name='group',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='last_name',
        ),
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
